# This file maps paths or patterns to labels using actions/labeler@v5 syntax
bug:
- changed-files:
  - any-glob-to-any-file: ['bug*', '**/*.test.*']

feature:
- changed-files:
  - any-glob-to-any-file: 'feature*'

enhancement:
- changed-files:
  - any-glob-to-any-file: 'enhancement*'

documentation:
- changed-files:
  - any-glob-to-any-file: ['docs/**', '**/*.md']

question:
- changed-files:
  - any-glob-to-any-file: 'question*'
