services:
  web:
    stdin_open: true # So that the serving is not exited with code 0
    image: yiddy/simple-countdown
    env_file: .env
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:3000/ >/dev/null || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
