services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TIMER_BACKGROUND: https://wallpaperplay.com/walls/full/0/7/6/29912.jpg
      TIMER_TARGET: 'Wed Oct 28 2020 00:00:00 GMT+0100' # Get help with https://esqsoft.com/javascript_examples/date-to-epoch.htm
      TIMER_TITLE: 'My birthday in'
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:3000/ >/dev/null || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
