name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Please provide as much detail as possible to help us diagnose and fix the issue.**

  - type: input
    id: bug-summary
    attributes:
      label: Summary
      description: Briefly summarize the bug
      placeholder: "Short description of the bug"
    validations:
      required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug
      placeholder: "1. Go to...\n2. Click on...\n3. See error"

  - type: textarea
    id: bug-expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe what should happen"

  - type: textarea
    id: bug-actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Describe what actually happened"

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link to any related issues, if applicable
      placeholder: "#12, #34"

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - Major
        - Minor
        - Trivial
      default: 2

  - type: input
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other info, logs, screenshots, or context
      placeholder: "Logs, screenshots, or other info"
    validations:
      required: false
