name: Copilot Control & Auto-Unassign

on:
  issue_comment:
    types: [created]
  issues:
    types: [labeled]

jobs:
  copilot-control:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Copilot Commands and Completion
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const repo = context.repo;
            const comment = context.payload.comment?.body?.toLowerCase() || "";
            const labels = context.payload.issue.labels.map(l => l.name.toLowerCase());

            // Map commands to labels
            const commandLabelMap = {
              "@copilot review": "copilot:review",
              "@copilot plan": "copilot:plan",
              "@copilot implement": "copilot:implement"
            };

            // Check for Copilot commands in comment
            let labelToAdd = null;
            for (const cmd in commandLabelMap) {
              if (comment.startsWith(cmd)) {
                labelToAdd = commandLabelMap[cmd];
                break;
              }
            }

            if (labelToAdd) {
              // Add label if not already present
              if (!labels.includes(labelToAdd.toLowerCase())) {
                await github.issues.addLabels({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: issue_number,
                  labels: [labelToAdd]
                });
              }

              // Assign Copilot
              await github.issues.addAssignees({
                owner: repo.owner,
                repo: repo.repo,
                issue_number: issue_number,
                assignees: ["github-copilot"]
              });

              console.log(`Assigned Copilot and added label: ${labelToAdd}`);
            }

            // Auto-unassign Copilot when work is finished
            // Consider a "copilot:done" label as a signal
            if (labels.includes("copilot:done")) {
              await github.issues.removeAssignees({
                owner: repo.owner,
                repo: repo.repo,
                issue_number: issue_number,
                assignees: ["github-copilot"]
              });

              console.log("Copilot work completed. Unassigned automatically.");
            }
