name: Create Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Download partial lint artifact
        uses: actions/download-artifact@v3
        with:
          name: partial-lint-results
          path: artifacts/partial-lint

      - name: Download full lint/build artifact
        uses: actions/download-artifact@v3
        with:
          name: full-lint-build-results
          path: artifacts/full-lint-build

      - name: Download Docker error artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-build-errors
          path: artifacts/docker-errors

      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Automated Issue Detected
          content-filepath: .github/artifacts/issue-template.md
          assignees: yiddytlq
          labels: automated, needs-review, error
