name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          export TIMER_BACKGROUND="${{ secrets.TIMER_BACKGROUND }}"
          export TIMER_TARGET="${{ secrets.TIMER_TARGET }}"
          export TIMER_TITLE="${{ secrets.TIMER_TITLE }}"

      - name: Apply variables.sh
        run: |
          chmod +x ./variables.sh
          ./variables.sh public

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com