name: Labeler

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml # points to your config
