name: Slack Notifications

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_run:
    workflows:
      - Docker Build & Publish
      - Lint & Build Checks
      - CI - CodeQL Scan
    types: [completed]
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine if workflow should notify
        id: decision
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            if [[ "${{ github.event.workflow_run.name }}" == "CI - CodeQL Scan" && "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
              echo "should_notify=false" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.workflow_run.name }}" == "Lint & Build Checks" && "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
              echo "should_notify=false" >> $GITHUB_OUTPUT
            else
              echo "should_notify=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_notify=true" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack Notification
        if: ${{ steps.decision.outputs.should_notify == 'true' }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action Notification*"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    *Event:* `${{ github.event_name }}`
                    *Repository:* <https://github.com/${{ github.repository }}|${{ github.repository }}>
                    *Workflow:* `${{ github.workflow }}`
                    *Status:* `${{ github.event.workflow_run.conclusion || job.status }}`
                    *Actor:* <https://github.com/${{ github.actor }}|${{ github.actor }}>
                    *URL:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|View Details>
