name: Slack Notifications

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_run:
    workflows:
      - Docker Build & Publish
      - CI - Lint & CodeQL Scan
    types: [completed]
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,ref,workflow,job,took,eventName
          mention: "" # set to 'here' or '@channel' if you want mentions
          # custom_payload: '{"text":"A GitHub event occurred."}' # optional custom message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
